### ISSUE TITLE
Links Not Populating

### ISSUE THREAD

**Issue by mattswymer** [Sigafoos/journal-links#9]
Installed the module and links are not auto-populating. Unsure what to do or who to contact.

![Capture](https://user-images.githubusercontent.com/39266139/94859171-1db85f00-0402-11eb-9c1c-eeee85795c14.JPG)

**Comment by mattswymer** [comment]
Nevermind. I was trying to link scenes. Your description doesn't say it works for that.

**Comment by Sigafoos** [comment]
@mattswymer are journals entries linked to scenes stored differently? If so I can probably add it fairly easily.

**Comment by mattswymer** [comment]
I realized my mistake. When I originally read "auto-populate" I got excited
and thought that this module would automatically link words to other
journals, scenes, actors, etc. I went and read the description more
thoroughly and realized that it creates the links at the bottom. It's still
awesome and I'm still going to use it, but I jumped to conclusions without
reading ahead.
